// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/user.api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserField int32

const (
	UserField_User_unknow UserField = 0
	UserField_User_id     UserField = 1
	UserField_User_name   UserField = 2
	UserField_User_age    UserField = 3
	UserField_User_sex    UserField = 4
	UserField_User_ctime  UserField = 5
	UserField_User_mtime  UserField = 6
)

// Enum value maps for UserField.
var (
	UserField_name = map[int32]string{
		0: "User_unknow",
		1: "User_id",
		2: "User_name",
		3: "User_age",
		4: "User_sex",
		5: "User_ctime",
		6: "User_mtime",
	}
	UserField_value = map[string]int32{
		"User_unknow": 0,
		"User_id":     1,
		"User_name":   2,
		"User_age":    3,
		"User_sex":    4,
		"User_ctime":  5,
		"User_mtime":  6,
	}
)

func (x UserField) Enum() *UserField {
	p := new(UserField)
	*p = x
	return p
}

func (x UserField) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserField) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_user_api_proto_enumTypes[0].Descriptor()
}

func (UserField) Type() protoreflect.EnumType {
	return &file_proto_user_api_proto_enumTypes[0]
}

func (x UserField) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserField.Descriptor instead.
func (UserField) EnumDescriptor() ([]byte, []int) {
	return file_proto_user_api_proto_rawDescGZIP(), []int{0}
}

type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" validate:"oneof 1 2 3"` // @gotags: validate:"oneof 1 2 3"
	// 名称|text|validate:"max=100,min=10"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" validate:"max=100,min=10"` // @gotags: validate:"max=100,min=10"
	// 年龄|number|validate:"max=140,min=18"
	Age int64 `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty" validate:"max=140,min=18"` // @gotags: validate:"max=140,min=18"
	// 性别|select|validate:"oneof=0 1 2"|0:女 1:男 2:无
	Sex int64 `protobuf:"varint,4,opt,name=sex,proto3" json:"sex,omitempty" validate:"oneof=0 1 2"` // @gotags: validate:"oneof=0 1 2"
	// 创建时间
	Ctime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=ctime,proto3" json:"ctime,omitempty"`
	// 更新时间
	Mtime         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=mtime,proto3" json:"mtime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_user_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_user_api_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetAge() int64 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *User) GetSex() int64 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *User) GetCtime() *timestamppb.Timestamp {
	if x != nil {
		return x.Ctime
	}
	return nil
}

func (x *User) GetMtime() *timestamppb.Timestamp {
	if x != nil {
		return x.Mtime
	}
	return nil
}

type UserId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserId) Reset() {
	*x = UserId{}
	mi := &file_proto_user_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserId) ProtoMessage() {}

func (x *UserId) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserId.ProtoReflect.Descriptor instead.
func (*UserId) Descriptor() ([]byte, []int) {
	return file_proto_user_api_proto_rawDescGZIP(), []int{1}
}

func (x *UserId) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Masks         []UserField            `protobuf:"varint,2,rep,packed,name=masks,proto3,enum=UserField" json:"masks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserReq) Reset() {
	*x = UpdateUserReq{}
	mi := &file_proto_user_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserReq) ProtoMessage() {}

func (x *UpdateUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserReq.ProtoReflect.Descriptor instead.
func (*UpdateUserReq) Descriptor() ([]byte, []int) {
	return file_proto_user_api_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateUserReq) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UpdateUserReq) GetMasks() []UserField {
	if x != nil {
		return x.Masks
	}
	return nil
}

type UserOrderBy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         UserField              `protobuf:"varint,1,opt,name=field,proto3,enum=UserField" json:"field,omitempty"`
	Desc          bool                   `protobuf:"varint,2,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserOrderBy) Reset() {
	*x = UserOrderBy{}
	mi := &file_proto_user_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserOrderBy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOrderBy) ProtoMessage() {}

func (x *UserOrderBy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOrderBy.ProtoReflect.Descriptor instead.
func (*UserOrderBy) Descriptor() ([]byte, []int) {
	return file_proto_user_api_proto_rawDescGZIP(), []int{3}
}

func (x *UserOrderBy) GetField() UserField {
	if x != nil {
		return x.Field
	}
	return UserField_User_unknow
}

func (x *UserOrderBy) GetDesc() bool {
	if x != nil {
		return x.Desc
	}
	return false
}

type UserFilterOr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       []*UserFilter          `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFilterOr) Reset() {
	*x = UserFilterOr{}
	mi := &file_proto_user_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFilterOr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFilterOr) ProtoMessage() {}

func (x *UserFilterOr) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFilterOr.ProtoReflect.Descriptor instead.
func (*UserFilterOr) Descriptor() ([]byte, []int) {
	return file_proto_user_api_proto_rawDescGZIP(), []int{4}
}

func (x *UserFilterOr) GetFilters() []*UserFilter {
	if x != nil {
		return x.Filters
	}
	return nil
}

type UserFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         UserField              `protobuf:"varint,1,opt,name=field,proto3,enum=UserField" json:"field,omitempty"`
	Op            string                 `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`
	Val           string                 `protobuf:"bytes,3,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFilter) Reset() {
	*x = UserFilter{}
	mi := &file_proto_user_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFilter) ProtoMessage() {}

func (x *UserFilter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFilter.ProtoReflect.Descriptor instead.
func (*UserFilter) Descriptor() ([]byte, []int) {
	return file_proto_user_api_proto_rawDescGZIP(), []int{5}
}

func (x *UserFilter) GetField() UserField {
	if x != nil {
		return x.Field
	}
	return UserField_User_unknow
}

func (x *UserFilter) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *UserFilter) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type ListUsersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Orderbys      []*UserOrderBy         `protobuf:"bytes,3,rep,name=orderbys,proto3" json:"orderbys,omitempty"`
	Filters       []*UserFilter          `protobuf:"bytes,4,rep,name=filters,proto3" json:"filters,omitempty"`
	SelectFields  []UserField            `protobuf:"varint,5,rep,packed,name=select_fields,json=selectFields,proto3,enum=UserField" json:"select_fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersReq) Reset() {
	*x = ListUsersReq{}
	mi := &file_proto_user_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersReq) ProtoMessage() {}

func (x *ListUsersReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersReq.ProtoReflect.Descriptor instead.
func (*ListUsersReq) Descriptor() ([]byte, []int) {
	return file_proto_user_api_proto_rawDescGZIP(), []int{6}
}

func (x *ListUsersReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUsersReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListUsersReq) GetOrderbys() []*UserOrderBy {
	if x != nil {
		return x.Orderbys
	}
	return nil
}

func (x *ListUsersReq) GetFilters() []*UserFilter {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *ListUsersReq) GetSelectFields() []UserField {
	if x != nil {
		return x.SelectFields
	}
	return nil
}

type ListUsersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	PageCount     int32                  `protobuf:"varint,3,opt,name=page_count,json=pageCount,proto3" json:"page_count,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResp) Reset() {
	*x = ListUsersResp{}
	mi := &file_proto_user_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResp) ProtoMessage() {}

func (x *ListUsersResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResp.ProtoReflect.Descriptor instead.
func (*ListUsersResp) Descriptor() ([]byte, []int) {
	return file_proto_user_api_proto_rawDescGZIP(), []int{7}
}

func (x *ListUsersResp) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResp) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListUsersResp) GetPageCount() int32 {
	if x != nil {
		return x.PageCount
	}
	return 0
}

func (x *ListUsersResp) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListUsersResp) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type UserCursor struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NextPageFilters []*UserFilterOr        `protobuf:"bytes,1,rep,name=next_page_filters,json=nextPageFilters,proto3" json:"next_page_filters,omitempty"`
	Orderbys        []*UserOrderBy         `protobuf:"bytes,2,rep,name=orderbys,proto3" json:"orderbys,omitempty"`
	Filters         []*UserFilter          `protobuf:"bytes,3,rep,name=filters,proto3" json:"filters,omitempty"`
	SelectFields    []UserField            `protobuf:"varint,4,rep,packed,name=select_fields,json=selectFields,proto3,enum=UserField" json:"select_fields,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserCursor) Reset() {
	*x = UserCursor{}
	mi := &file_proto_user_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCursor) ProtoMessage() {}

func (x *UserCursor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCursor.ProtoReflect.Descriptor instead.
func (*UserCursor) Descriptor() ([]byte, []int) {
	return file_proto_user_api_proto_rawDescGZIP(), []int{8}
}

func (x *UserCursor) GetNextPageFilters() []*UserFilterOr {
	if x != nil {
		return x.NextPageFilters
	}
	return nil
}

func (x *UserCursor) GetOrderbys() []*UserOrderBy {
	if x != nil {
		return x.Orderbys
	}
	return nil
}

func (x *UserCursor) GetFilters() []*UserFilter {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *UserCursor) GetSelectFields() []UserField {
	if x != nil {
		return x.SelectFields
	}
	return nil
}

type ListUsersMoreReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageToken     string                 `protobuf:"bytes,1,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Cursor        *UserCursor            `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersMoreReq) Reset() {
	*x = ListUsersMoreReq{}
	mi := &file_proto_user_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersMoreReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersMoreReq) ProtoMessage() {}

func (x *ListUsersMoreReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersMoreReq.ProtoReflect.Descriptor instead.
func (*ListUsersMoreReq) Descriptor() ([]byte, []int) {
	return file_proto_user_api_proto_rawDescGZIP(), []int{9}
}

func (x *ListUsersMoreReq) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListUsersMoreReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListUsersMoreReq) GetCursor() *UserCursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

type ListUsersMoreResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextPageToken string                 `protobuf:"bytes,1,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	Users         []*User                `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersMoreResp) Reset() {
	*x = ListUsersMoreResp{}
	mi := &file_proto_user_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersMoreResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersMoreResp) ProtoMessage() {}

func (x *ListUsersMoreResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersMoreResp.ProtoReflect.Descriptor instead.
func (*ListUsersMoreResp) Descriptor() ([]byte, []int) {
	return file_proto_user_api_proto_rawDescGZIP(), []int{10}
}

func (x *ListUsersMoreResp) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListUsersMoreResp) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersMoreResp) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

var File_proto_user_api_proto protoreflect.FileDescriptor

const file_proto_user_api_proto_rawDesc = "" +
	"\n" +
	"\x14proto/user.api.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb2\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x03R\x03age\x12\x10\n" +
	"\x03sex\x18\x04 \x01(\x03R\x03sex\x120\n" +
	"\x05ctime\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x05ctime\x120\n" +
	"\x05mtime\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x05mtime\"\x18\n" +
	"\x06UserId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"L\n" +
	"\rUpdateUserReq\x12\x19\n" +
	"\x04user\x18\x01 \x01(\v2\x05.UserR\x04user\x12 \n" +
	"\x05masks\x18\x02 \x03(\x0e2\n" +
	".UserFieldR\x05masks\"C\n" +
	"\vUserOrderBy\x12 \n" +
	"\x05field\x18\x01 \x01(\x0e2\n" +
	".UserFieldR\x05field\x12\x12\n" +
	"\x04desc\x18\x02 \x01(\bR\x04desc\"5\n" +
	"\fUserFilterOr\x12%\n" +
	"\afilters\x18\x01 \x03(\v2\v.UserFilterR\afilters\"P\n" +
	"\n" +
	"UserFilter\x12 \n" +
	"\x05field\x18\x01 \x01(\x0e2\n" +
	".UserFieldR\x05field\x12\x0e\n" +
	"\x02op\x18\x02 \x01(\tR\x02op\x12\x10\n" +
	"\x03val\x18\x03 \x01(\tR\x03val\"\xc1\x01\n" +
	"\fListUsersReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12(\n" +
	"\borderbys\x18\x03 \x03(\v2\f.UserOrderByR\borderbys\x12%\n" +
	"\afilters\x18\x04 \x03(\v2\v.UserFilterR\afilters\x12/\n" +
	"\rselect_fields\x18\x05 \x03(\x0e2\n" +
	".UserFieldR\fselectFields\"\x9d\x01\n" +
	"\rListUsersResp\x12\x1b\n" +
	"\x05users\x18\x01 \x03(\v2\x05.UserR\x05users\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x1d\n" +
	"\n" +
	"page_count\x18\x03 \x01(\x05R\tpageCount\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\"\xc9\x01\n" +
	"\n" +
	"UserCursor\x129\n" +
	"\x11next_page_filters\x18\x01 \x03(\v2\r.UserFilterOrR\x0fnextPageFilters\x12(\n" +
	"\borderbys\x18\x02 \x03(\v2\f.UserOrderByR\borderbys\x12%\n" +
	"\afilters\x18\x03 \x03(\v2\v.UserFilterR\afilters\x12/\n" +
	"\rselect_fields\x18\x04 \x03(\x0e2\n" +
	".UserFieldR\fselectFields\"s\n" +
	"\x10ListUsersMoreReq\x12\x1d\n" +
	"\n" +
	"page_token\x18\x01 \x01(\tR\tpageToken\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12#\n" +
	"\x06cursor\x18\x03 \x01(\v2\v.UserCursorR\x06cursor\"s\n" +
	"\x11ListUsersMoreResp\x12&\n" +
	"\x0fnext_page_token\x18\x01 \x01(\tR\rnextPageToken\x12\x1b\n" +
	"\x05users\x18\x02 \x03(\v2\x05.UserR\x05users\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore*t\n" +
	"\tUserField\x12\x0f\n" +
	"\vUser_unknow\x10\x00\x12\v\n" +
	"\aUser_id\x10\x01\x12\r\n" +
	"\tUser_name\x10\x02\x12\f\n" +
	"\bUser_age\x10\x03\x12\f\n" +
	"\bUser_sex\x10\x04\x12\x0e\n" +
	"\n" +
	"User_ctime\x10\x05\x12\x0e\n" +
	"\n" +
	"User_mtime\x10\x062\xfc\x01\n" +
	"\vUserService\x12\x1a\n" +
	"\n" +
	"CreateUser\x12\x05.User\x1a\x05.User\x12-\n" +
	"\n" +
	"DeleteUser\x12\a.UserId\x1a\x16.google.protobuf.Empty\x12#\n" +
	"\n" +
	"UpdateUser\x12\x0e.UpdateUserReq\x1a\x05.User\x12\x19\n" +
	"\aGetUser\x12\a.UserId\x1a\x05.User\x12*\n" +
	"\tListUsers\x12\r.ListUsersReq\x1a\x0e.ListUsersResp\x126\n" +
	"\rListUsersMore\x12\x11.ListUsersMoreReq\x1a\x12.ListUsersMoreRespB\x06Z\x04/apib\x06proto3"

var (
	file_proto_user_api_proto_rawDescOnce sync.Once
	file_proto_user_api_proto_rawDescData []byte
)

func file_proto_user_api_proto_rawDescGZIP() []byte {
	file_proto_user_api_proto_rawDescOnce.Do(func() {
		file_proto_user_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_api_proto_rawDesc), len(file_proto_user_api_proto_rawDesc)))
	})
	return file_proto_user_api_proto_rawDescData
}

var file_proto_user_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_user_api_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_user_api_proto_goTypes = []any{
	(UserField)(0),                // 0: UserField
	(*User)(nil),                  // 1: User
	(*UserId)(nil),                // 2: UserId
	(*UpdateUserReq)(nil),         // 3: UpdateUserReq
	(*UserOrderBy)(nil),           // 4: UserOrderBy
	(*UserFilterOr)(nil),          // 5: UserFilterOr
	(*UserFilter)(nil),            // 6: UserFilter
	(*ListUsersReq)(nil),          // 7: ListUsersReq
	(*ListUsersResp)(nil),         // 8: ListUsersResp
	(*UserCursor)(nil),            // 9: UserCursor
	(*ListUsersMoreReq)(nil),      // 10: ListUsersMoreReq
	(*ListUsersMoreResp)(nil),     // 11: ListUsersMoreResp
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 13: google.protobuf.Empty
}
var file_proto_user_api_proto_depIdxs = []int32{
	12, // 0: User.ctime:type_name -> google.protobuf.Timestamp
	12, // 1: User.mtime:type_name -> google.protobuf.Timestamp
	1,  // 2: UpdateUserReq.user:type_name -> User
	0,  // 3: UpdateUserReq.masks:type_name -> UserField
	0,  // 4: UserOrderBy.field:type_name -> UserField
	6,  // 5: UserFilterOr.filters:type_name -> UserFilter
	0,  // 6: UserFilter.field:type_name -> UserField
	4,  // 7: ListUsersReq.orderbys:type_name -> UserOrderBy
	6,  // 8: ListUsersReq.filters:type_name -> UserFilter
	0,  // 9: ListUsersReq.select_fields:type_name -> UserField
	1,  // 10: ListUsersResp.users:type_name -> User
	5,  // 11: UserCursor.next_page_filters:type_name -> UserFilterOr
	4,  // 12: UserCursor.orderbys:type_name -> UserOrderBy
	6,  // 13: UserCursor.filters:type_name -> UserFilter
	0,  // 14: UserCursor.select_fields:type_name -> UserField
	9,  // 15: ListUsersMoreReq.cursor:type_name -> UserCursor
	1,  // 16: ListUsersMoreResp.users:type_name -> User
	1,  // 17: UserService.CreateUser:input_type -> User
	2,  // 18: UserService.DeleteUser:input_type -> UserId
	3,  // 19: UserService.UpdateUser:input_type -> UpdateUserReq
	2,  // 20: UserService.GetUser:input_type -> UserId
	7,  // 21: UserService.ListUsers:input_type -> ListUsersReq
	10, // 22: UserService.ListUsersMore:input_type -> ListUsersMoreReq
	1,  // 23: UserService.CreateUser:output_type -> User
	13, // 24: UserService.DeleteUser:output_type -> google.protobuf.Empty
	1,  // 25: UserService.UpdateUser:output_type -> User
	1,  // 26: UserService.GetUser:output_type -> User
	8,  // 27: UserService.ListUsers:output_type -> ListUsersResp
	11, // 28: UserService.ListUsersMore:output_type -> ListUsersMoreResp
	23, // [23:29] is the sub-list for method output_type
	17, // [17:23] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_proto_user_api_proto_init() }
func file_proto_user_api_proto_init() {
	if File_proto_user_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_api_proto_rawDesc), len(file_proto_user_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_api_proto_goTypes,
		DependencyIndexes: file_proto_user_api_proto_depIdxs,
		EnumInfos:         file_proto_user_api_proto_enumTypes,
		MessageInfos:      file_proto_user_api_proto_msgTypes,
	}.Build()
	File_proto_user_api_proto = out.File
	file_proto_user_api_proto_goTypes = nil
	file_proto_user_api_proto_depIdxs = nil
}
